### ISSUE TITLE
Database schemas for api

### ISSUE THREAD

**Issue by ang-st** [OmniLayer/omniapi#1]
Hello, 
I try to setup the api but db schemas seems are lacking, i add some success by using https://github.com/OmniLayer/omniEngine/tree/master/database 

yet it seems that https://github.com/OmniLayer/omniEngine/blob/master/database/omni_db_schema.psql#L29 is lacking Mastercoin enum value that is required (at least) here : https://github.com/OmniLayer/omniapi/blob/master/api/balancehelper.py#L32

does this enum value still required or can it be removed from sql query ?

**Comment by achamely** [comment]
hey @ang-st  thanks for the feedback. The enum is an artifact leftover from before we did the migration from 'Mastercoin' to 'Omni' and still had both data elements in the database. 
I've gone ahead and cleaned it up/removed it as it was no longer used / had already been properly replaced with 'Omni'.  If you pull from master you should get the update.
If you have any other questions let us know otherwise feel free to close this out

**Comment by ang-st** [comment]
@achamely :+1:  thanks
Just to be sure `omniapi` is intended to work with `omniEngine` for indexing transaction or you intend to merge those at some point ?

**Comment by achamely** [comment]
@ang-st  correct. we abstracted out the projects purposely to maintain separate and cleaner code bases
Omnicore is the reference client and blockchain client It has rpc interfaces and if you are already running/using it is generally you need to reference/query information. 

Omniengine is an external parsing engine designed to grab the data from omnicore and populate/store it in a database for applications/situations where you need more robust access to the data and different / additional interaction methodologies. 

OmniApi is a frontend to serve that database data up in a usable fashion for our web applications Omniwallet (our web wallet) and OmniExplorer (our block explorer)
