### ISSUE TITLE
Help with Api

### ISSUE THREAD

**Issue by santos177** [OmniLayer/omniapi#5]
Hello @achamely :

I'm trying to turn on the omniapi (and the omniEngine) but im stuck  in the GET / POST request. For example: when i call curl -X GET -H "Content-Type: application/x-www-form-urlencoded" "server_ip/v2/properties/list" the response is something by default. The other calls https://api.omniexplorer.info showed here, doesn't work properly (in some cases i can see 502 and 405 errors).  I don't now exactly where start to debugging. I would like some help with this, because for me is not enought with the present documentation. My goal is get the omnicored connected with the omniEngine and the omniapi locally , and receive request from outside.

Best Regards!

**Comment by achamely** [comment]
@santos177 everything related to setting up the database and updating it is in the OmniEngine project. That is the guts and brain behind the database. 
Most of the documentation is actually listed under Omniwallet repo : https://github.com/OmniLayer/omniwallet#ubuntu-setup  
Specifically check the ubuntu-setup section for descriptions of the layout and then the manual install section for more in depth information. 

I would recommend you start there to ensure you have the database setup and defined properly and that your omniengine is running/updating your database accordingly
Once your database is actually being populated your api should be able to be configured to read from it and serve up info. 
Unfortunately due to the many components of the project there is no 'default' answer for why something doesn't work. Any troubleshooting is likely going to be a multipart process to determine where the issue is occuring.
